---
service_name: 'prometheus'
app_name: "{{ service_name }}-apb"

# Prometheus
prometheus_image: "registry.access.redhat.com/openshift3/prometheus"
prometheus_version: "latest"
prometheus_port: 9090
prometheus_configmap_name: "{{ service_name }}-configmap"
prometheus_configmap_rules_name: "{{ service_name }}-rules"
prometheus_configmap_volume_name: "{{ service_name }}-configmap-volume"
prometheus_data_volume_name: "{{ service_name }}-data"
prometheus_pvc_name: "{{ service_name }}-claim"
prometheus_secret_name: "prometheus"

# Addons
## Oauth-Proxy
service_name_proxy: "{{ service_name }}-proxy"
prometheus_proxy_image: 'registry.access.redhat.com/openshift3/oauth-proxy'
prometheus_proxy_version: 'latest'
prometheus_proxy_container_port: 8443
prometheus_proxy_svc_port: 443
prometheus_proxy_tls_secret_name: "{{ service_name_proxy }}-tls"
prometheus_proxy_configmap_oauth_name: "{{ service_name_proxy }}-oauth-configmap"
prometheus_proxy_tls_skip_verify: 'true'
prometheus_proxy_cookie_secret: 'SECRET'

## AlertManager
service_name_am: "{{ service_name }}-alertmanager"
prometheus_alertmanager_image: 'registry.access.redhat.com/openshift3/prometheus-alertmanager'
prometheus_alertmanager_version: 'latest'
prometheus_alertmanager_configmap_name: "{{ service_name_am }}-config-map"
prometheus_alertmanager_configmap_templates_name: "{{ service_name_am }}-templates-configmap"
prometheus_alertmanager_data_volume_name: "{{ service_name_am }}-data"
prometheus_alertmanager_port: 9093
prometheus_alertmanager_pvc_name: "{{ service_name_am }}-claim"

## Grafana
service_name_graf: "{{ service_name }}-grafana"
prometheus_grafana_image: 'docker.io/grafana/grafana'
prometheus_grafana_version: 'latest'
prometheus_grafana_configmap_name: "{{ service_name_graf }}-config-map"
prometheus_grafana_configmap_templates_name: "{{ service_name_graf }}-templates-configmap"
prometheus_grafana_data_volume_name: "{{ service_name_graf }}-data"
prometheus_grafana_port: 3000
prometheus_grafana_pvc_name: "{{ service_name_graf }}-claim"

## Grafana Oauth-Proxy
service_name_graf_proxy: "{{ service_name_graf }}-proxy"
prometheus_grafana_proxy_image: 'registry.access.redhat.com/openshift3/oauth-proxy'
prometheus_grafana_proxy_version: 'latest'
prometheus_grafana_proxy_container_port: 8443
prometheus_grafana_proxy_svc_port: 443
prometheus_grafana_proxy_tls_secret_name: "{{ service_name_graf_proxy }}-tls"
prometheus_grafana_proxy_configmap_oauth_name: "{{ service_name_graf_proxy }}-oauth-configmap"
prometheus_grafana_proxy_tls_skip_verify: 'true'
prometheus_grafana_proxy_cookie_secret: 'SECRET'
prometheus_grafana_datasource_payload:
  name: "{{ item.name | default('Sample') }}"
  type: "{{ item.type | default('prometheus') }}"
  typeLogoUrl: ''
  access: "{{ item.proxy | default('proxy') }}"
  url: "{{ item.url | default('https://prometheus_url') }}"
  basicAuth: false
  withCredentials: false
  jsonData:
    tlsSkipVerify: true
    token: "{{ item.token | default('') }}"

## AlertBuffer
prometheus_alertbuffer_image: 'registry.access.redhat.com/openshift3/prometheus-alert-buffer'
prometheus_alertbuffer_version: 'latest'


